#include "Arithmatic.h"
#include "Branching.cpp"
void JMP(string);
void JC(string);
void JNC(string);
void JZ(string);
void JNZ(string);
void JP(string);
void JM(string);
void JPE(string);
void JPO(string);
